ZipCode.create([{:code => "3700", :name => "Rønne", },
                {:code => "3720", :name => "Aakirkeby", },
                {:code => "3730", :name => "Nexø", },
                {:code => "3740", :name => "Svaneke", },
                {:code => "3751", :name => "Østermarie", },
                {:code => "3760", :name => "Gudhjem", },
                {:code => "3770", :name => "Allinge", },
                {:code => "3782", :name => "Klemensker", },
                {:code => "3790", :name => "Hasle", },
                {:code => "2960", :name => "Rungsted Kyst", },
                {:code => "2970", :name => "Hørsholm", },
                {:code => "2980", :name => "Kokkedal", },
                {:code => "2990", :name => "Nivå", },
                {:code => "3000", :name => "Helsingør", },
                {:code => "3050", :name => "Humlebæk", },
                {:code => "3060", :name => "Espergærde", },
                {:code => "3070", :name => "Snekkersten", },
                {:code => "3080", :name => "Tikøb", },
                {:code => "3100", :name => "Hornbæk", },
                {:code => "3120", :name => "Dronningmølle", },
                {:code => "3140", :name => "Ålsgårde", },
                {:code => "3150", :name => "Hellebæk", },
                {:code => "3200", :name => "Helsinge", },
                {:code => "3210", :name => "Vejby", },
                {:code => "3220", :name => "Tisvildeleje", },
                {:code => "3230", :name => "Græsted", },
                {:code => "3250", :name => "Gilleleje", },
                {:code => "3300", :name => "Frederiksværk", },
                {:code => "3310", :name => "Ølsted", },
                {:code => "3320", :name => "Skævinge", },
                {:code => "3330", :name => "Gørløse", },
                {:code => "3360", :name => "Liseleje", },
                {:code => "3370", :name => "Melby", },
                {:code => "3390", :name => "Hundested", },
                {:code => "3400", :name => "Hillerød", },
                {:code => "3450", :name => "Allerød", },
                {:code => "3460", :name => "Birkerød", },
                {:code => "3480", :name => "Fredensborg", },
                {:code => "3490", :name => "Kvistgård", },
                {:code => "3520", :name => "Farum", },
                {:code => "3540", :name => "Lynge", },
                {:code => "3550", :name => "Slangerup", },
                {:code => "3600", :name => "Frederikssund", },
                {:code => "3630", :name => "Jægerspris", },
                {:code => "3650", :name => "Ølstykke", },
                {:code => "3660", :name => "Stenløse", },
                {:code => "3670", :name => "Veksø Sjælland", },
                {:code => "4050", :name => "Skibby", },
                {:code => "5000", :name => "Odense C", },
                {:code => "5200", :name => "Odense V", },
                {:code => "5210", :name => "Odense NV", },
                {:code => "5220", :name => "Odense SØ", },
                {:code => "5230", :name => "Odense M", },
                {:code => "5240", :name => "Odense NØ", },
                {:code => "5250", :name => "Odense SV", },
                {:code => "5260", :name => "Odense S", },
                {:code => "5270", :name => "Odense N", },
                {:code => "5290", :name => "Marslev", },
                {:code => "5300", :name => "Kerteminde", },
                {:code => "5320", :name => "Agedrup", },
                {:code => "5330", :name => "Munkebo", },
                {:code => "5350", :name => "Rynkeby", },
                {:code => "5370", :name => "Mesinge", },
                {:code => "5380", :name => "Dalby", },
                {:code => "5390", :name => "Martofte", },
                {:code => "5400", :name => "Bogense", },
                {:code => "5450", :name => "Otterup", },
                {:code => "5462", :name => "Morud", },
                {:code => "5463", :name => "Harndrup", },
                {:code => "5464", :name => "Brenderup Fyn", },
                {:code => "5466", :name => "Asperup", },
                {:code => "5471", :name => "Søndersø", },
                {:code => "5474", :name => "Veflinge", },
                {:code => "5485", :name => "Skamby", },
                {:code => "5491", :name => "Blommenslyst", },
                {:code => "5492", :name => "Vissenbjerg", },
                {:code => "5500", :name => "Middelfart", },
                {:code => "5540", :name => "Ullerslev", },
                {:code => "5550", :name => "Langeskov", },
                {:code => "5560", :name => "Aarup", },
                {:code => "5580", :name => "Nørre Aaby", },
                {:code => "5591", :name => "Gelsted", },
                {:code => "5592", :name => "Ejby", },
                {:code => "5600", :name => "Faaborg", },
                {:code => "5610", :name => "Assens", },
                {:code => "5620", :name => "Glamsbjerg", },
                {:code => "5631", :name => "Ebberup", },
                {:code => "5642", :name => "Millinge", },
                {:code => "5672", :name => "Broby", },
                {:code => "5683", :name => "Haarby", },
                {:code => "5690", :name => "Tommerup", },
                {:code => "5700", :name => "Svendborg", },
                {:code => "5750", :name => "Ringe", },
                {:code => "5762", :name => "Vester Skerninge", },
                {:code => "5771", :name => "Stenstrup", },
                {:code => "5772", :name => "Kværndrup", },
                {:code => "5792", :name => "Årslev", },
                {:code => "5800", :name => "Nyborg", },
                {:code => "5853", :name => "Ørbæk", },
                {:code => "5854", :name => "Gislev", },
                {:code => "5856", :name => "Ryslinge", },
                {:code => "5863", :name => "Ferritslev Fyn", },
                {:code => "5871", :name => "Frørup", },
                {:code => "5874", :name => "Hesselager", },
                {:code => "5881", :name => "Skårup Fyn", },
                {:code => "5882", :name => "Vejstrup", },
                {:code => "5883", :name => "Oure", },
                {:code => "5884", :name => "Gudme", },
                {:code => "5892", :name => "Gudbjerg Sydfyn", },
                {:code => "5900", :name => "Rudkøbing", },
                {:code => "5932", :name => "Humble", },
                {:code => "5935", :name => "Bagenkop", },
                {:code => "5953", :name => "Tranekær", },
                {:code => "5960", :name => "Marstal", },
                {:code => "5970", :name => "Ærøskøbing", },
                {:code => "5985", :name => "Søby Ærø", },
                {:code => "877", :name => "København C", },
                {:code => "900", :name => "København C", },
                {:code => "910", :name => "København C", },
                {:code => "929", :name => "København C", },
                {:code => "999", :name => "København C", },
                {:code => "1000", :name => "København K", },
                {:code => "1001", :name => "København K", },
                {:code => "1002", :name => "København K", },
                {:code => "1003", :name => "København K", },
                {:code => "1004", :name => "København K", },
                {:code => "1005", :name => "København K", },
                {:code => "1006", :name => "København K", },
                {:code => "1007", :name => "København K", },
                {:code => "1008", :name => "København K", },
                {:code => "1009", :name => "København K", },
                {:code => "1010", :name => "København K", },
                {:code => "1011", :name => "København K", },
                {:code => "1012", :name => "København K", },
                {:code => "1013", :name => "København K", },
                {:code => "1014", :name => "København K", },
                {:code => "1015", :name => "København K", },
                {:code => "1016", :name => "København K", },
                {:code => "1017", :name => "København K", },
                {:code => "1018", :name => "København K", },
                {:code => "1019", :name => "København K", },
                {:code => "1020", :name => "København K", },
                {:code => "1021", :name => "København K", },
                {:code => "1022", :name => "København K", },
                {:code => "1023", :name => "København K", },
                {:code => "1024", :name => "København K", },
                {:code => "1025", :name => "København K", },
                {:code => "1026", :name => "København K", },
                {:code => "1045", :name => "København K", },
                {:code => "1050", :name => "København K", },
                {:code => "1051", :name => "København K", },
                {:code => "1052", :name => "København K", },
                {:code => "1053", :name => "København K", },
                {:code => "1054", :name => "København K", },
                {:code => "1055", :name => "København K", },
                {:code => "1056", :name => "København K", },
                {:code => "1057", :name => "København K", },
                {:code => "1058", :name => "København K", },
                {:code => "1059", :name => "København K", },
                {:code => "1060", :name => "København K", },
                {:code => "1061", :name => "København K", },
                {:code => "1062", :name => "København K", },
                {:code => "1063", :name => "København K", },
                {:code => "1064", :name => "København K", },
                {:code => "1065", :name => "København K", },
                {:code => "1066", :name => "København K", },
                {:code => "1067", :name => "København K", },
                {:code => "1068", :name => "København K", },
                {:code => "1069", :name => "København K", },
                {:code => "1070", :name => "København K", },
                {:code => "1071", :name => "København K", },
                {:code => "1072", :name => "København K", },
                {:code => "1073", :name => "København K", },
                {:code => "1074", :name => "København K", },
                {:code => "1092", :name => "København K", },
                {:code => "1093", :name => "København K", },
                {:code => "1095", :name => "København K", },
                {:code => "1098", :name => "København K", },
                {:code => "1100", :name => "København K", },
                {:code => "1101", :name => "København K", },
                {:code => "1102", :name => "København K", },
                {:code => "1103", :name => "København K", },
                {:code => "1104", :name => "København K", },
                {:code => "1105", :name => "København K", },
                {:code => "1106", :name => "København K", },
                {:code => "1107", :name => "København K", },
                {:code => "1110", :name => "København K", },
                {:code => "1111", :name => "København K", },
                {:code => "1112", :name => "København K", },
                {:code => "1113", :name => "København K", },
                {:code => "1114", :name => "København K", },
                {:code => "1115", :name => "København K", },
                {:code => "1116", :name => "København K", },
                {:code => "1117", :name => "København K", },
                {:code => "1118", :name => "København K", },
                {:code => "1119", :name => "København K", },
                {:code => "1120", :name => "København K", },
                {:code => "1121", :name => "København K", },
                {:code => "1122", :name => "København K", },
                {:code => "1123", :name => "København K", },
                {:code => "1124", :name => "København K", },
                {:code => "1125", :name => "København K", },
                {:code => "1126", :name => "København K", },
                {:code => "1127", :name => "København K", },
                {:code => "1128", :name => "København K", },
                {:code => "1129", :name => "København K", },
                {:code => "1130", :name => "København K", },
                {:code => "1131", :name => "København K", },
                {:code => "1140", :name => "København K", },
                {:code => "1147", :name => "København K", },
                {:code => "1148", :name => "København K", },
                {:code => "1150", :name => "København K", },
                {:code => "1151", :name => "København K", },
                {:code => "1152", :name => "København K", },
                {:code => "1153", :name => "København K", },
                {:code => "1154", :name => "København K", },
                {:code => "1155", :name => "København K", },
                {:code => "1156", :name => "København K", },
                {:code => "1157", :name => "København K", },
                {:code => "1158", :name => "København K", },
                {:code => "1159", :name => "København K", },
                {:code => "1160", :name => "København K", },
                {:code => "1161", :name => "København K", },
                {:code => "1162", :name => "København K", },
                {:code => "1163", :name => "København K", },
                {:code => "1164", :name => "København K", },
                {:code => "1165", :name => "København K", },
                {:code => "1166", :name => "København K", },
                {:code => "1167", :name => "København K", },
                {:code => "1168", :name => "København K", },
                {:code => "1169", :name => "København K", },
                {:code => "1170", :name => "København K", },
                {:code => "1171", :name => "København K", },
                {:code => "1172", :name => "København K", },
                {:code => "1173", :name => "København K", },
                {:code => "1174", :name => "København K", },
                {:code => "1175", :name => "København K", },
                {:code => "1200", :name => "København K", },
                {:code => "1201", :name => "København K", },
                {:code => "1202", :name => "København K", },
                {:code => "1203", :name => "København K", },
                {:code => "1204", :name => "København K", },
                {:code => "1205", :name => "København K", },
                {:code => "1206", :name => "København K", },
                {:code => "1207", :name => "København K", },
                {:code => "1208", :name => "København K", },
                {:code => "1209", :name => "København K", },
                {:code => "1210", :name => "København K", },
                {:code => "1211", :name => "København K", },
                {:code => "1212", :name => "København K", },
                {:code => "1213", :name => "København K", },
                {:code => "1214", :name => "København K", },
                {:code => "1215", :name => "København K", },
                {:code => "1216", :name => "København K", },
                {:code => "1217", :name => "København K", },
                {:code => "1218", :name => "København K", },
                {:code => "1219", :name => "København K", },
                {:code => "1220", :name => "København K", },
                {:code => "1221", :name => "København K", },
                {:code => "1240", :name => "København K", },
                {:code => "1250", :name => "København K", },
                {:code => "1251", :name => "København K", },
                {:code => "1252", :name => "København K", },
                {:code => "1253", :name => "København K", },
                {:code => "1254", :name => "København K", },
                {:code => "1255", :name => "København K", },
                {:code => "1256", :name => "København K", },
                {:code => "1257", :name => "København K", },
                {:code => "1258", :name => "København K", },
                {:code => "1259", :name => "København K", },
                {:code => "1260", :name => "København K", },
                {:code => "1261", :name => "København K", },
                {:code => "1263", :name => "København K", },
                {:code => "1264", :name => "København K", },
                {:code => "1265", :name => "København K", },
                {:code => "1266", :name => "København K", },
                {:code => "1267", :name => "København K", },
                {:code => "1268", :name => "København K", },
                {:code => "1270", :name => "København K", },
                {:code => "1271", :name => "København K", },
                {:code => "1291", :name => "København K", },
                {:code => "1300", :name => "København K", },
                {:code => "1301", :name => "København K", },
                {:code => "1302", :name => "København K", },
                {:code => "1303", :name => "København K", },
                {:code => "1304", :name => "København K", },
                {:code => "1306", :name => "København K", },
                {:code => "1307", :name => "København K", },
                {:code => "1308", :name => "København K", },
                {:code => "1309", :name => "København K", },
                {:code => "1310", :name => "København K", },
                {:code => "1311", :name => "København K", },
                {:code => "1312", :name => "København K", },
                {:code => "1313", :name => "København K", },
                {:code => "1314", :name => "København K", },
                {:code => "1315", :name => "København K", },
                {:code => "1316", :name => "København K", },
                {:code => "1317", :name => "København K", },
                {:code => "1318", :name => "København K", },
                {:code => "1319", :name => "København K", },
                {:code => "1320", :name => "København K", },
                {:code => "1321", :name => "København K", },
                {:code => "1322", :name => "København K", },
                {:code => "1323", :name => "København K", },
                {:code => "1324", :name => "København K", },
                {:code => "1325", :name => "København K", },
                {:code => "1326", :name => "København K", },
                {:code => "1327", :name => "København K", },
                {:code => "1328", :name => "København K", },
                {:code => "1329", :name => "København K", },
                {:code => "1349", :name => "København K", },
                {:code => "1350", :name => "København K", },
                {:code => "1352", :name => "København K", },
                {:code => "1353", :name => "København K", },
                {:code => "1354", :name => "København K", },
                {:code => "1355", :name => "København K", },
                {:code => "1356", :name => "København K", },
                {:code => "1357", :name => "København K", },
                {:code => "1358", :name => "København K", },
                {:code => "1359", :name => "København K", },
                {:code => "1360", :name => "København K", },
                {:code => "1361", :name => "København K", },
                {:code => "1362", :name => "København K", },
                {:code => "1363", :name => "København K", },
                {:code => "1364", :name => "København K", },
                {:code => "1365", :name => "København K", },
                {:code => "1366", :name => "København K", },
                {:code => "1367", :name => "København K", },
                {:code => "1368", :name => "København K", },
                {:code => "1369", :name => "København K", },
                {:code => "1370", :name => "København K", },
                {:code => "1371", :name => "København K", },
                {:code => "1400", :name => "København K", },
                {:code => "1401", :name => "København K", },
                {:code => "1402", :name => "København K", },
                {:code => "1403", :name => "København K", },
                {:code => "1404", :name => "København K", },
                {:code => "1406", :name => "København K", },
                {:code => "1407", :name => "København K", },
                {:code => "1408", :name => "København K", },
                {:code => "1409", :name => "København K", },
                {:code => "1410", :name => "København K", },
                {:code => "1411", :name => "København K", },
                {:code => "1412", :name => "København K", },
                {:code => "1413", :name => "København K", },
                {:code => "1414", :name => "København K", },
                {:code => "1415", :name => "København K", },
                {:code => "1416", :name => "København K", },
                {:code => "1417", :name => "København K", },
                {:code => "1418", :name => "København K", },
                {:code => "1419", :name => "København K", },
                {:code => "1420", :name => "København K", },
                {:code => "1421", :name => "København K", },
                {:code => "1422", :name => "København K", },
                {:code => "1423", :name => "København K", },
                {:code => "1424", :name => "København K", },
                {:code => "1425", :name => "København K", },
                {:code => "1426", :name => "København K", },
                {:code => "1427", :name => "København K", },
                {:code => "1428", :name => "København K", },
                {:code => "1429", :name => "København K", },
                {:code => "1430", :name => "København K", },
                {:code => "1431", :name => "København K", },
                {:code => "1432", :name => "København K", },
                {:code => "1433", :name => "København K", },
                {:code => "1434", :name => "København K", },
                {:code => "1435", :name => "København K", },
                {:code => "1436", :name => "København K", },
                {:code => "1437", :name => "København K", },
                {:code => "1438", :name => "København K", },
                {:code => "1439", :name => "København K", },
                {:code => "1440", :name => "København K", },
                {:code => "1441", :name => "København K", },
                {:code => "1448", :name => "København K", },
                {:code => "1450", :name => "København K", },
                {:code => "1451", :name => "København K", },
                {:code => "1452", :name => "København K", },
                {:code => "1453", :name => "København K", },
                {:code => "1454", :name => "København K", },
                {:code => "1455", :name => "København K", },
                {:code => "1456", :name => "København K", },
                {:code => "1457", :name => "København K", },
                {:code => "1458", :name => "København K", },
                {:code => "1459", :name => "København K", },
                {:code => "1460", :name => "København K", },
                {:code => "1461", :name => "København K", },
                {:code => "1462", :name => "København K", },
                {:code => "1463", :name => "København K", },
                {:code => "1464", :name => "København K", },
                {:code => "1465", :name => "København K", },
                {:code => "1466", :name => "København K", },
                {:code => "1467", :name => "København K", },
                {:code => "1468", :name => "København K", },
                {:code => "1470", :name => "København K", },
                {:code => "1471", :name => "København K", },
                {:code => "1472", :name => "København K", },
                {:code => "1473", :name => "København K", },
                {:code => "1500", :name => "København V", },
                {:code => "1501", :name => "København V", },
                {:code => "1502", :name => "København V", },
                {:code => "1503", :name => "København V", },
                {:code => "1504", :name => "København V", },
                {:code => "1505", :name => "København V", },
                {:code => "1506", :name => "København V", },
                {:code => "1507", :name => "København V", },
                {:code => "1508", :name => "København V", },
                {:code => "1509", :name => "København V", },
                {:code => "1510", :name => "København V", },
                {:code => "1532", :name => "København V", },
                {:code => "1533", :name => "København V", },
                {:code => "1550", :name => "København V", },
                {:code => "1551", :name => "København V", },
                {:code => "1552", :name => "København V", },
                {:code => "1553", :name => "København V", },
                {:code => "1554", :name => "København V", },
                {:code => "1555", :name => "København V", },
                {:code => "1556", :name => "København V", },
                {:code => "1557", :name => "København V", },
                {:code => "1558", :name => "København V", },
                {:code => "1559", :name => "København V", },
                {:code => "1560", :name => "København V", },
                {:code => "1561", :name => "København V", },
                {:code => "1562", :name => "København V", },
                {:code => "1563", :name => "København V", },
                {:code => "1564", :name => "København V", },
                {:code => "1566", :name => "København V", },
                {:code => "1567", :name => "København V", },
                {:code => "1568", :name => "København V", },
                {:code => "1569", :name => "København V", },
                {:code => "1570", :name => "København V", },
                {:code => "1571", :name => "København V", },
                {:code => "1572", :name => "København V", },
                {:code => "1573", :name => "København V", },
                {:code => "1574", :name => "København V", },
                {:code => "1575", :name => "København V", },
                {:code => "1576", :name => "København V", },
                {:code => "1577", :name => "København V", },
                {:code => "1592", :name => "København V", },
                {:code => "1599", :name => "København V", },
                {:code => "1600", :name => "København V", },
                {:code => "1601", :name => "København V", },
                {:code => "1602", :name => "København V", },
                {:code => "1603", :name => "København V", },
                {:code => "1604", :name => "København V", },
                {:code => "1605", :name => "København V", },
                {:code => "1606", :name => "København V", },
                {:code => "1607", :name => "København V", },
                {:code => "1608", :name => "København V", },
                {:code => "1609", :name => "København V", },
                {:code => "1610", :name => "København V", },
                {:code => "1611", :name => "København V", },
                {:code => "1612", :name => "København V", },
                {:code => "1613", :name => "København V", },
                {:code => "1614", :name => "København V", },
                {:code => "1615", :name => "København V", },
                {:code => "1616", :name => "København V", },
                {:code => "1617", :name => "København V", },
                {:code => "1618", :name => "København V", },
                {:code => "1619", :name => "København V", },
                {:code => "1620", :name => "København V", },
                {:code => "1621", :name => "København V", },
                {:code => "1622", :name => "København V", },
                {:code => "1623", :name => "København V", },
                {:code => "1624", :name => "København V", },
                {:code => "1630", :name => "København V", },
                {:code => "1631", :name => "København V", },
                {:code => "1632", :name => "København V", },
                {:code => "1633", :name => "København V", },
                {:code => "1634", :name => "København V", },
                {:code => "1635", :name => "København V", },
                {:code => "1640", :name => "København V", },
                {:code => "1650", :name => "København V", },
                {:code => "1651", :name => "København V", },
                {:code => "1652", :name => "København V", },
                {:code => "1653", :name => "København V", },
                {:code => "1654", :name => "København V", },
                {:code => "1655", :name => "København V", },
                {:code => "1656", :name => "København V", },
                {:code => "1657", :name => "København V", },
                {:code => "1658", :name => "København V", },
                {:code => "1659", :name => "København V", },
                {:code => "1660", :name => "København V", },
                {:code => "1661", :name => "København V", },
                {:code => "1662", :name => "København V", },
                {:code => "1663", :name => "København V", },
                {:code => "1664", :name => "København V", },
                {:code => "1665", :name => "København V", },
                {:code => "1666", :name => "København V", },
                {:code => "1667", :name => "København V", },
                {:code => "1668", :name => "København V", },
                {:code => "1669", :name => "København V", },
                {:code => "1670", :name => "København V", },
                {:code => "1671", :name => "København V", },
                {:code => "1672", :name => "København V", },
                {:code => "1673", :name => "København V", },
                {:code => "1674", :name => "København V", },
                {:code => "1675", :name => "København V", },
                {:code => "1676", :name => "København V", },
                {:code => "1677", :name => "København V", },
                {:code => "1699", :name => "København V", },
                {:code => "1700", :name => "København V", },
                {:code => "1701", :name => "København V", },
                {:code => "1702", :name => "København V", },
                {:code => "1703", :name => "København V", },
                {:code => "1704", :name => "København V", },
                {:code => "1705", :name => "København V", },
                {:code => "1706", :name => "København V", },
                {:code => "1707", :name => "København V", },
                {:code => "1708", :name => "København V", },
                {:code => "1709", :name => "København V", },
                {:code => "1710", :name => "København V", },
                {:code => "1711", :name => "København V", },
                {:code => "1712", :name => "København V", },
                {:code => "1713", :name => "København V", },
                {:code => "1714", :name => "København V", },
                {:code => "1715", :name => "København V", },
                {:code => "1716", :name => "København V", },
                {:code => "1717", :name => "København V", },
                {:code => "1718", :name => "København V", },
                {:code => "1719", :name => "København V", },
                {:code => "1720", :name => "København V", },
                {:code => "1721", :name => "København V", },
                {:code => "1722", :name => "København V", },
                {:code => "1723", :name => "København V", },
                {:code => "1724", :name => "København V", },
                {:code => "1725", :name => "København V", },
                {:code => "1726", :name => "København V", },
                {:code => "1727", :name => "København V", },
                {:code => "1728", :name => "København V", },
                {:code => "1729", :name => "København V", },
                {:code => "1730", :name => "København V", },
                {:code => "1731", :name => "København V", },
                {:code => "1732", :name => "København V", },
                {:code => "1733", :name => "København V", },
                {:code => "1734", :name => "København V", },
                {:code => "1735", :name => "København V", },
                {:code => "1736", :name => "København V", },
                {:code => "1737", :name => "København V", },
                {:code => "1738", :name => "København V", },
                {:code => "1739", :name => "København V", },
                {:code => "1749", :name => "København V", },
                {:code => "1750", :name => "København V", },
                {:code => "1751", :name => "København V", },
                {:code => "1752", :name => "København V", },
                {:code => "1753", :name => "København V", },
                {:code => "1754", :name => "København V", },
                {:code => "1755", :name => "København V", },
                {:code => "1756", :name => "København V", },
                {:code => "1757", :name => "København V", },
                {:code => "1758", :name => "København V", },
                {:code => "1759", :name => "København V", },
                {:code => "1760", :name => "København V", },
                {:code => "1761", :name => "København V", },
                {:code => "1762", :name => "København V", },
                {:code => "1763", :name => "København V", },
                {:code => "1764", :name => "København V", },
                {:code => "1765", :name => "København V", },
                {:code => "1766", :name => "København V", },
                {:code => "1770", :name => "København V", },
                {:code => "1771", :name => "København V", },
                {:code => "1772", :name => "København V", },
                {:code => "1773", :name => "København V", },
                {:code => "1774", :name => "København V", },
                {:code => "1775", :name => "København V", },
                {:code => "1777", :name => "København V", },
                {:code => "1780", :name => "København V", },
                {:code => "1782", :name => "København V", },
                {:code => "1785", :name => "København V", },
                {:code => "1786", :name => "København V", },
                {:code => "1787", :name => "København V", },
                {:code => "1790", :name => "København V", },
                {:code => "1799", :name => "København V", },
                {:code => "1800", :name => "Frederiksberg C", },
                {:code => "1801", :name => "Frederiksberg C", },
                {:code => "1802", :name => "Frederiksberg C", },
                {:code => "1803", :name => "Frederiksberg C", },
                {:code => "1804", :name => "Frederiksberg C", },
                {:code => "1805", :name => "Frederiksberg C", },
                {:code => "1806", :name => "Frederiksberg C", },
                {:code => "1807", :name => "Frederiksberg C", },
                {:code => "1808", :name => "Frederiksberg C", },
                {:code => "1809", :name => "Frederiksberg C", },
                {:code => "1810", :name => "Frederiksberg C", },
                {:code => "1811", :name => "Frederiksberg C", },
                {:code => "1812", :name => "Frederiksberg C", },
                {:code => "1813", :name => "Frederiksberg C", },
                {:code => "1814", :name => "Frederiksberg C", },
                {:code => "1815", :name => "Frederiksberg C", },
                {:code => "1816", :name => "Frederiksberg C", },
                {:code => "1817", :name => "Frederiksberg C", },
                {:code => "1818", :name => "Frederiksberg C", },
                {:code => "1819", :name => "Frederiksberg C", },
                {:code => "1820", :name => "Frederiksberg C", },
                {:code => "1822", :name => "Frederiksberg C", },
                {:code => "1823", :name => "Frederiksberg C", },
                {:code => "1824", :name => "Frederiksberg C", },
                {:code => "1825", :name => "Frederiksberg C", },
                {:code => "1826", :name => "Frederiksberg C", },
                {:code => "1827", :name => "Frederiksberg C", },
                {:code => "1828", :name => "Frederiksberg C", },
                {:code => "1829", :name => "Frederiksberg C", },
                {:code => "1835", :name => "Frederiksberg C", },
                {:code => "1850", :name => "Frederiksberg C", },
                {:code => "1851", :name => "Frederiksberg C", },
                {:code => "1852", :name => "Frederiksberg C", },
                {:code => "1853", :name => "Frederiksberg C", },
                {:code => "1854", :name => "Frederiksberg C", },
                {:code => "1855", :name => "Frederiksberg C", },
                {:code => "1856", :name => "Frederiksberg C", },
                {:code => "1857", :name => "Frederiksberg C", },
                {:code => "1860", :name => "Frederiksberg C", },
                {:code => "1861", :name => "Frederiksberg C", },
                {:code => "1862", :name => "Frederiksberg C", },
                {:code => "1863", :name => "Frederiksberg C", },
                {:code => "1864", :name => "Frederiksberg C", },
                {:code => "1865", :name => "Frederiksberg C", },
                {:code => "1866", :name => "Frederiksberg C", },
                {:code => "1867", :name => "Frederiksberg C", },
                {:code => "1868", :name => "Frederiksberg C", },
                {:code => "1870", :name => "Frederiksberg C", },
                {:code => "1871", :name => "Frederiksberg C", },
                {:code => "1872", :name => "Frederiksberg C", },
                {:code => "1873", :name => "Frederiksberg C", },
                {:code => "1874", :name => "Frederiksberg C", },
                {:code => "1875", :name => "Frederiksberg C", },
                {:code => "1876", :name => "Frederiksberg C", },
                {:code => "1877", :name => "Frederiksberg C", },
                {:code => "1878", :name => "Frederiksberg C", },
                {:code => "1879", :name => "Frederiksberg C", },
                {:code => "1900", :name => "Frederiksberg C", },
                {:code => "1901", :name => "Frederiksberg C", },
                {:code => "1902", :name => "Frederiksberg C", },
                {:code => "1903", :name => "Frederiksberg C", },
                {:code => "1904", :name => "Frederiksberg C", },
                {:code => "1905", :name => "Frederiksberg C", },
                {:code => "1906", :name => "Frederiksberg C", },
                {:code => "1908", :name => "Frederiksberg C", },
                {:code => "1909", :name => "Frederiksberg C", },
                {:code => "1910", :name => "Frederiksberg C", },
                {:code => "1911", :name => "Frederiksberg C", },
                {:code => "1912", :name => "Frederiksberg C", },
                {:code => "1913", :name => "Frederiksberg C", },
                {:code => "1914", :name => "Frederiksberg C", },
                {:code => "1915", :name => "Frederiksberg C", },
                {:code => "1916", :name => "Frederiksberg C", },
                {:code => "1917", :name => "Frederiksberg C", },
                {:code => "1920", :name => "Frederiksberg C", },
                {:code => "1921", :name => "Frederiksberg C", },
                {:code => "1922", :name => "Frederiksberg C", },
                {:code => "1923", :name => "Frederiksberg C", },
                {:code => "1924", :name => "Frederiksberg C", },
                {:code => "1925", :name => "Frederiksberg C", },
                {:code => "1926", :name => "Frederiksberg C", },
                {:code => "1927", :name => "Frederiksberg C", },
                {:code => "1928", :name => "Frederiksberg C", },
                {:code => "1931", :name => "Frederiksberg C", },
                {:code => "1950", :name => "Frederiksberg C", },
                {:code => "1951", :name => "Frederiksberg C", },
                {:code => "1952", :name => "Frederiksberg C", },
                {:code => "1953", :name => "Frederiksberg C", },
                {:code => "1954", :name => "Frederiksberg C", },
                {:code => "1955", :name => "Frederiksberg C", },
                {:code => "1956", :name => "Frederiksberg C", },
                {:code => "1957", :name => "Frederiksberg C", },
                {:code => "1958", :name => "Frederiksberg C", },
                {:code => "1959", :name => "Frederiksberg C", },
                {:code => "1960", :name => "Frederiksberg C", },
                {:code => "1961", :name => "Frederiksberg C", },
                {:code => "1962", :name => "Frederiksberg C", },
                {:code => "1963", :name => "Frederiksberg C", },
                {:code => "1964", :name => "Frederiksberg C", },
                {:code => "1965", :name => "Frederiksberg C", },
                {:code => "1966", :name => "Frederiksberg C", },
                {:code => "1967", :name => "Frederiksberg C", },
                {:code => "1970", :name => "Frederiksberg C", },
                {:code => "1971", :name => "Frederiksberg C", },
                {:code => "1972", :name => "Frederiksberg C", },
                {:code => "1973", :name => "Frederiksberg C", },
                {:code => "1974", :name => "Frederiksberg C", },
                {:code => "2000", :name => "Frederiksberg", },
                {:code => "2100", :name => "København Ø", },
                {:code => "2150", :name => "Nordhavn", },
                {:code => "2200", :name => "København N", },
                {:code => "2300", :name => "København S", },
                {:code => "2400", :name => "København NV", },
                {:code => "2450", :name => "København SV", },
                {:code => "2500", :name => "Valby", },
                {:code => "2600", :name => "Glostrup", },
                {:code => "2605", :name => "Brøndby", },
                {:code => "2610", :name => "Rødovre", },
                {:code => "2620", :name => "Albertslund", },
                {:code => "2625", :name => "Vallensbæk", },
                {:code => "2630", :name => "Taastrup", },
                {:code => "2635", :name => "Ishøj", },
                {:code => "2640", :name => "Hedehusene", },
                {:code => "2650", :name => "Hvidovre", },
                {:code => "2660", :name => "Brøndby Strand", },
                {:code => "2665", :name => "Vallensbæk Strand", },
                {:code => "2700", :name => "Brønshøj", },
                {:code => "2720", :name => "Vanløse", },
                {:code => "2730", :name => "Herlev", },
                {:code => "2740", :name => "Skovlunde", },
                {:code => "2750", :name => "Ballerup", },
                {:code => "2760", :name => "Måløv", },
                {:code => "2765", :name => "Smørum", },
                {:code => "2770", :name => "Kastrup", },
                {:code => "2791", :name => "Dragør", },
                {:code => "2800", :name => "Kongens Lyngby", },
                {:code => "2820", :name => "Gentofte", },
                {:code => "2830", :name => "Virum", },
                {:code => "2840", :name => "Holte", },
                {:code => "2850", :name => "Nærum", },
                {:code => "2860", :name => "Søborg", },
                {:code => "2870", :name => "Dyssegård", },
                {:code => "2880", :name => "Bagsværd", },
                {:code => "2900", :name => "Hellerup", },
                {:code => "2920", :name => "Charlottenlund", },
                {:code => "2930", :name => "Klampenborg", },
                {:code => "2942", :name => "Skodsborg", },
                {:code => "2950", :name => "Vedbæk", },
                {:code => "3500", :name => "Værløse", },
                {:code => "9000", :name => "Aalborg", },
                {:code => "9200", :name => "Aalborg SV", },
                {:code => "9210", :name => "Aalborg SØ", },
                {:code => "9220", :name => "Aalborg Øst", },
                {:code => "9230", :name => "Svenstrup J", },
                {:code => "9240", :name => "Nibe", },
                {:code => "9260", :name => "Gistrup", },
                {:code => "9270", :name => "Klarup", },
                {:code => "9280", :name => "Storvorde", },
                {:code => "9293", :name => "Kongerslev", },
                {:code => "9300", :name => "Sæby", },
                {:code => "9310", :name => "Vodskov", },
                {:code => "9320", :name => "Hjallerup", },
                {:code => "9330", :name => "Dronninglund", },
                {:code => "9340", :name => "Asaa", },
                {:code => "9352", :name => "Dybvad", },
                {:code => "9362", :name => "Gandrup", },
                {:code => "9370", :name => "Hals", },
                {:code => "9380", :name => "Vestbjerg", },
                {:code => "9381", :name => "Sulsted", },
                {:code => "9382", :name => "Tylstrup", },
                {:code => "9400", :name => "Nørresundby", },
                {:code => "9430", :name => "Vadum", },
                {:code => "9440", :name => "Aabybro", },
                {:code => "9460", :name => "Brovst", },
                {:code => "9480", :name => "Løkken", },
                {:code => "9490", :name => "Pandrup", },
                {:code => "9492", :name => "Blokhus", },
                {:code => "9493", :name => "Saltum", },
                {:code => "9500", :name => "Hobro", },
                {:code => "9510", :name => "Arden", },
                {:code => "9520", :name => "Skørping", },
                {:code => "9530", :name => "Støvring", },
                {:code => "9541", :name => "Suldrup", },
                {:code => "9560", :name => "Hadsund", },
                {:code => "9574", :name => "Bælum", },
                {:code => "9575", :name => "Terndrup", },
                {:code => "9600", :name => "Aars", },
                {:code => "9610", :name => "Nørager", },
                {:code => "9640", :name => "Farsø", },
                {:code => "9670", :name => "Løgstør", },
                {:code => "9681", :name => "Ranum", },
                {:code => "9690", :name => "Fjerritslev", },
                {:code => "9700", :name => "Brønderslev", },
                {:code => "9740", :name => "Jerslev J", },
                {:code => "9750", :name => "Øster Vrå", },
                {:code => "9760", :name => "Vrå", },
                {:code => "9800", :name => "Hjørring", },
                {:code => "9830", :name => "Tårs", },
                {:code => "9850", :name => "Hirtshals", },
                {:code => "9870", :name => "Sindal", },
                {:code => "9881", :name => "Bindslev", },
                {:code => "9900", :name => "Frederikshavn", },
                {:code => "9940", :name => "Læsø", },
                {:code => "9970", :name => "Strandby", },
                {:code => "9981", :name => "Jerup", },
                {:code => "9982", :name => "Ålbæk", },
                {:code => "9990", :name => "Skagen", },
                {:code => "6600", :name => "Vejen", },
                {:code => "6621", :name => "Gesten", },
                {:code => "6622", :name => "Bække", },
                {:code => "6623", :name => "Vorbasse", },
                {:code => "6650", :name => "Brørup", },
                {:code => "6670", :name => "Holsted", },
                {:code => "6682", :name => "Hovborg", },
                {:code => "6683", :name => "Føvling", },
                {:code => "6690", :name => "Gørding", },
                {:code => "6700", :name => "Esbjerg", },
                {:code => "6705", :name => "Esbjerg Ø", },
                {:code => "6710", :name => "Esbjerg V", },
                {:code => "6715", :name => "Esbjerg N", },
                {:code => "6720", :name => "Fanø", },
                {:code => "6731", :name => "Tjæreborg", },
                {:code => "6740", :name => "Bramming", },
                {:code => "6752", :name => "Glejbjerg", },
                {:code => "6753", :name => "Agerbæk", },
                {:code => "6760", :name => "Ribe", },
                {:code => "6771", :name => "Gredstedbro", },
                {:code => "6800", :name => "Varde", },
                {:code => "6818", :name => "Årre", },
                {:code => "6823", :name => "Ansager", },
                {:code => "6830", :name => "Nørre Nebel", },
                {:code => "6840", :name => "Oksbøl", },
                {:code => "6851", :name => "Janderup Vestj", },
                {:code => "6852", :name => "Billum", },
                {:code => "6853", :name => "Vejers Strand", },
                {:code => "6854", :name => "Henne", },
                {:code => "6857", :name => "Blåvand", },
                {:code => "6862", :name => "Tistrup", },
                {:code => "6870", :name => "Ølgod", },
                {:code => "7190", :name => "Billund", },
                {:code => "7200", :name => "Grindsted", },
                {:code => "7250", :name => "Hejnsvig", },
                {:code => "7260", :name => "Sønder Omme", },
                {:code => "6880", :name => "Tarm", },
                {:code => "6893", :name => "Hemmet", },
                {:code => "6900", :name => "Skjern", },
                {:code => "6920", :name => "Videbæk", },
                {:code => "6933", :name => "Kibæk", },
                {:code => "6940", :name => "Lem St", },
                {:code => "6950", :name => "Ringkøbing", },
                {:code => "6960", :name => "Hvide Sande", },
                {:code => "6971", :name => "Spjald", },
                {:code => "6973", :name => "Ørnhøj", },
                {:code => "6980", :name => "Tim", },
                {:code => "6990", :name => "Ulfborg", },
                {:code => "7280", :name => "Sønder Felding", },
                {:code => "7330", :name => "Brande", },
                {:code => "7400", :name => "Herning", },
                {:code => "7430", :name => "Ikast", },
                {:code => "7441", :name => "Bording", },
                {:code => "7442", :name => "Engesvang", },
                {:code => "7451", :name => "Sunds", },
                {:code => "7480", :name => "Vildbjerg", },
                {:code => "7490", :name => "Aulum", },
                {:code => "7500", :name => "Holstebro", },
                {:code => "7540", :name => "Haderup", },
                {:code => "7550", :name => "Sørvad", },
                {:code => "7560", :name => "Hjerm", },
                {:code => "7570", :name => "Vemb", },
                {:code => "7600", :name => "Struer", },
                {:code => "7620", :name => "Lemvig", },
                {:code => "7650", :name => "Bøvlingbjerg", },
                {:code => "7660", :name => "Bækmarksbro", },
                {:code => "7673", :name => "Harboøre", },
                {:code => "7680", :name => "Thyborøn", },
                {:code => "7790", :name => "Thyholm", },
                {:code => "7830", :name => "Vinderup", },
                {:code => "7270", :name => "Stakroge", },
                {:code => "2670", :name => "Greve", },
                {:code => "2680", :name => "Solrød Strand", },
                {:code => "2690", :name => "Karlslunde", },
                {:code => "4000", :name => "Roskilde", },
                {:code => "4030", :name => "Tune", },
                {:code => "4040", :name => "Jyllinge", },
                {:code => "4060", :name => "Kirke Såby", },
                {:code => "4070", :name => "Kirke Hyllinge", },
                {:code => "4130", :name => "Viby Sjælland", },
                {:code => "4140", :name => "Borup", },
                {:code => "4173", :name => "Fjenneslev", },
                {:code => "4320", :name => "Lejre", },
                {:code => "4330", :name => "Hvalsø", },
                {:code => "4600", :name => "Køge", },
                {:code => "4621", :name => "Gadstrup", },
                {:code => "4622", :name => "Havdrup", },
                {:code => "4623", :name => "Lille Skensved", },
                {:code => "4632", :name => "Bjæverskov", },
                {:code => "4652", :name => "Hårlev", },
                {:code => "4671", :name => "Strøby", },
                {:code => "4681", :name => "Herfølge", },
                {:code => "4682", :name => "Tureby", },
                {:code => "4160", :name => "Herlufmagle", },
                {:code => "4171", :name => "Glumsø", },
                {:code => "4640", :name => "Fakse", },
                {:code => "4653", :name => "Karise", },
                {:code => "4654", :name => "Fakse Ladeplads", },
                {:code => "4660", :name => "Store Heddinge", },
                {:code => "4672", :name => "Klippinge", },
                {:code => "4673", :name => "Rødvig Stevns", },
                {:code => "4683", :name => "Rønnede", },
                {:code => "4684", :name => "Holmegaard", },
                {:code => "4700", :name => "Næstved", },
                {:code => "4720", :name => "Præstø", },
                {:code => "4733", :name => "Tappernøje", },
                {:code => "4735", :name => "Mern", },
                {:code => "4736", :name => "Karrebæksminde", },
                {:code => "4750", :name => "Lundby", },
                {:code => "4760", :name => "Vordingborg", },
                {:code => "4771", :name => "Kalvehave", },
                {:code => "4772", :name => "Langebæk", },
                {:code => "4773", :name => "Stensved", },
                {:code => "4780", :name => "Stege", },
                {:code => "4791", :name => "Borre", },
                {:code => "4792", :name => "Askeby", },
                {:code => "4793", :name => "Bogø By", },
                {:code => "4800", :name => "Nykøbing Falster", },
                {:code => "4840", :name => "Nørre Alslev", },
                {:code => "4850", :name => "Stubbekøbing", },
                {:code => "4862", :name => "Guldborg", },
                {:code => "4863", :name => "Eskilstrup", },
                {:code => "4871", :name => "Horbelev", },
                {:code => "4872", :name => "Idestrup", },
                {:code => "4873", :name => "Væggerløse", },
                {:code => "4874", :name => "Gedser", },
                {:code => "4880", :name => "Nysted", },
                {:code => "4891", :name => "Toreby L", },
                {:code => "4892", :name => "Kettinge", },
                {:code => "4894", :name => "Øster Ulslev", },
                {:code => "4895", :name => "Errindlev", },
                {:code => "4900", :name => "Nakskov", },
                {:code => "4912", :name => "Harpelunde", },
                {:code => "4913", :name => "Horslunde", },
                {:code => "4920", :name => "Søllested", },
                {:code => "4930", :name => "Maribo", },
                {:code => "4941", :name => "Bandholm", },
                {:code => "4943", :name => "Torrig L", },
                {:code => "4944", :name => "Fejø", },
                {:code => "4951", :name => "Nørreballe", },
                {:code => "4952", :name => "Stokkemarke", },
                {:code => "4953", :name => "Vesterborg", },
                {:code => "4960", :name => "Holeby", },
                {:code => "4970", :name => "Rødby", },
                {:code => "4983", :name => "Dannemare", },
                {:code => "4990", :name => "Sakskøbing", },
                { :code => "6070", :name => "Christiansfeld", },
                { :code => "6093", :name => "Sjølund", },
                { :code => "6094", :name => "Hejls", },
                { :code => "6100", :name => "Haderslev", },
                { :code => "6200", :name => "Aabenraa", },
                { :code => "6230", :name => "Rødekro", },
                { :code => "6240", :name => "Løgumkloster", },
                { :code => "6261", :name => "Bredebro", },
                { :code => "6270", :name => "Tønder", },
                { :code => "6280", :name => "Højer", },
                { :code => "6300", :name => "Gråsten", },
                { :code => "6310", :name => "Broager", },
                { :code => "6320", :name => "Egernsund", },
                { :code => "6330", :name => "Padborg", },
                { :code => "6340", :name => "Kruså", },
                { :code => "6360", :name => "Tinglev", },
                { :code => "6372", :name => "Bylderup-Bov", },
                { :code => "6392", :name => "Bolderslev", },
                { :code => "6400", :name => "Sønderborg", },
                { :code => "6430", :name => "Nordborg", },
                { :code => "6440", :name => "Augustenborg", },
                { :code => "6470", :name => "Sydals", },
                { :code => "6500", :name => "Vojens", },
                { :code => "6510", :name => "Gram", },
                { :code => "6520", :name => "Toftlund", },
                { :code => "6534", :name => "Agerskov", },
                { :code => "6535", :name => "Branderup J", },
                { :code => "6541", :name => "Bevtoft", },
                { :code => "6560", :name => "Sommersted", },
                { :code => "6630", :name => "Rødding", },
                { :code => "6660", :name => "Lintrup", },
                { :code => "6780", :name => "Skærbæk", },
                { :code => "6792", :name => "Rømø", },
                { :code => "6000", :name => "Kolding", },
                { :code => "6040", :name => "Egtved", },
                { :code => "6051", :name => "Almind", },
                { :code => "6052", :name => "Viuf", },
                { :code => "6064", :name => "Jordrup", },
                { :code => "6091", :name => "Bjert", },
                { :code => "6092", :name => "Sønder Stenderup", },
                { :code => "6580", :name => "Vamdrup", },
                { :code => "6640", :name => "Lunderskov", },
                { :code => "7000", :name => "Fredericia", },
                { :code => "7080", :name => "Børkop", },
                { :code => "7100", :name => "Vejle", },
                { :code => "7120", :name => "Vejle Øst", },
                { :code => "7130", :name => "Juelsminde", },
                { :code => "7140", :name => "Stouby", },
                { :code => "7150", :name => "Barrit", },
                { :code => "7160", :name => "Tørring", },
                { :code => "7171", :name => "Uldum", },
                { :code => "7173", :name => "Vonge", },
                { :code => "7182", :name => "Bredsten", },
                { :code => "7183", :name => "Randbøl", },
                { :code => "7184", :name => "Vandel", },
                { :code => "7300", :name => "Jelling", },
                { :code => "7321", :name => "Gadbjerg", },
                { :code => "7323", :name => "Give", },
                { :code => "7361", :name => "Ejstrupholm", },
                { :code => "7362", :name => "Hampen", },
                { :code => "8700", :name => "Horsens", },
                { :code => "8721", :name => "Daugård", },
                { :code => "8722", :name => "Hedensted", },
                { :code => "8723", :name => "Løsning", },
                { :code => "8732", :name => "Hovedgård", },
                { :code => "8740", :name => "Brædstrup", },
                { :code => "8751", :name => "Gedved", },
                { :code => "8752", :name => "Østbirk", },
                { :code => "8762", :name => "Flemming", },
                { :code => "8763", :name => "Rask Mølle", },
                { :code => "8765", :name => "Klovborg", },
                { :code => "8766", :name => "Nørre Snede", },
                { :code => "8781", :name => "Stenderup", },
                { :code => "8783", :name => "Hornsyld", },
                { :code => "4100", :name => "Ringsted", },
                { :code => "4174", :name => "Jystrup Midtsj", },
                { :code => "4180", :name => "Sorø", },
                { :code => "4190", :name => "Munke Bjergby", },
                { :code => "4200", :name => "Slagelse", },
                { :code => "4220", :name => "Korsør", },
                { :code => "4230", :name => "Skælskør", },
                { :code => "4241", :name => "Vemmelev", },
                { :code => "4242", :name => "Boeslunde", },
                { :code => "4243", :name => "Rude", },
                { :code => "4250", :name => "Fuglebjerg", },
                { :code => "4261", :name => "Dalmose", },
                { :code => "4262", :name => "Sandved", },
                { :code => "4270", :name => "Høng", },
                { :code => "4281", :name => "Gørlev", },
                { :code => "4291", :name => "Ruds Vedby", },
                { :code => "4293", :name => "Dianalund", },
                { :code => "4295", :name => "Stenlille", },
                { :code => "4296", :name => "Nyrup", },
                { :code => "4300", :name => "Holbæk", },
                { :code => "4340", :name => "Tølløse", },
                { :code => "4350", :name => "Ugerløse", },
                { :code => "4360", :name => "Kirke Eskilstrup", },
                { :code => "4370", :name => "Store Merløse", },
                { :code => "4390", :name => "Vipperød", },
                { :code => "4400", :name => "Kalundborg", },
                { :code => "4420", :name => "Regstrup", },
                { :code => "4440", :name => "Mørkøv", },
                { :code => "4450", :name => "Jyderup", },
                { :code => "4460", :name => "Snertinge", },
                { :code => "4470", :name => "Svebølle", },
                { :code => "4480", :name => "Store Fuglede", },
                { :code => "4490", :name => "Jerslev Sjælland", },
                { :code => "4500", :name => "Nykøbing Sjælland", },
                { :code => "4520", :name => "Svinninge", },
                { :code => "4532", :name => "Gislinge", },
                { :code => "4534", :name => "Hørve", },
                { :code => "4540", :name => "Fårevejle", },
                { :code => "4550", :name => "Asnæs", },
                { :code => "4560", :name => "Vig", },
                { :code => "4571", :name => "Grevinge", },
                { :code => "4572", :name => "Nørre Asmindrup", },
                { :code => "4573", :name => "Højby", },
                { :code => "4581", :name => "Rørvig", },
                { :code => "4583", :name => "Sjællands Odde", },
                { :code => "4591", :name => "Føllenslev", },
                { :code => "4592", :name => "Sejerø", },
                { :code => "4593", :name => "Eskebjerg", },
                { :code => "4690", :name => "Haslev", },
                { :code => "6855", :name => "Outrup", },
                { :code => "7470", :name => "Karup J", },
                { :code => "7700", :name => "Thisted", },
                { :code => "7730", :name => "Hanstholm", },
                { :code => "7741", :name => "Frøstrup", },
                { :code => "7742", :name => "Vesløs", },
                { :code => "7752", :name => "Snedsted", },
                { :code => "7755", :name => "Bedsted Thy", },
                { :code => "7760", :name => "Hurup Thy", },
                { :code => "7770", :name => "Vestervig", },
                { :code => "7800", :name => "Skive", },
                { :code => "7840", :name => "Højslev", },
                { :code => "7850", :name => "Stoholm Jyll", },
                { :code => "7860", :name => "Spøttrup", },
                { :code => "7870", :name => "Roslev", },
                { :code => "7884", :name => "Fur", },
                { :code => "7900", :name => "Nykøbing Mors", },
                { :code => "7950", :name => "Erslev", },
                { :code => "7960", :name => "Karby", },
                { :code => "7970", :name => "Redsted M", },
                { :code => "7980", :name => "Vils", },
                { :code => "7990", :name => "Øster Assels", },
                { :code => "8620", :name => "Kjellerup", },
                { :code => "8643", :name => "Ans By", },
                { :code => "8800", :name => "Viborg", },
                { :code => "8830", :name => "Tjele", },
                { :code => "8831", :name => "Løgstrup", },
                { :code => "8832", :name => "Skals", },
                { :code => "8840", :name => "Rødkærsbro", },
                { :code => "8850", :name => "Bjerringbro", },
                { :code => "8860", :name => "Ulstrup", },
                { :code => "8881", :name => "Thorsø", },
                { :code => "9620", :name => "Aalestrup", },
                { :code => "9631", :name => "Gedsted", },
                { :code => "9632", :name => "Møldrup", },
                { :code => "8000", :name => "Århus C", },
                { :code => "8200", :name => "Århus N", },
                { :code => "8210", :name => "Århus V", },
                { :code => "8220", :name => "Brabrand", },
                { :code => "8230", :name => "Åbyhøj", },
                { :code => "8240", :name => "Risskov", },
                { :code => "8245", :name => "Risskov Ø", },
                { :code => "8250", :name => "Egå", },
                { :code => "8260", :name => "Viby J", },
                { :code => "8270", :name => "Højbjerg", },
                { :code => "8300", :name => "Odder", },
                { :code => "8305", :name => "Samsø", },
                { :code => "8310", :name => "Tranbjerg J", },
                { :code => "8320", :name => "Mårslet", },
                { :code => "8330", :name => "Beder", },
                { :code => "8340", :name => "Malling", },
                { :code => "8350", :name => "Hundslund", },
                { :code => "8355", :name => "Solbjerg", },
                { :code => "8361", :name => "Hasselager", },
                { :code => "8362", :name => "Hørning", },
                { :code => "8370", :name => "Hadsten", },
                { :code => "8380", :name => "Trige", },
                { :code => "8381", :name => "Tilst", },
                { :code => "8382", :name => "Hinnerup", },
                { :code => "8400", :name => "Ebeltoft", },
                { :code => "8410", :name => "Rønde", },
                { :code => "8420", :name => "Knebel", },
                { :code => "8444", :name => "Balle", },
                { :code => "8450", :name => "Hammel", },
                { :code => "8462", :name => "Harlev J", },
                { :code => "8464", :name => "Galten", },
                { :code => "8471", :name => "Sabro", },
                { :code => "8472", :name => "Sporup", },
                { :code => "8500", :name => "Grenaa", },
                { :code => "8520", :name => "Lystrup", },
                { :code => "8530", :name => "Hjortshøj", },
                { :code => "8541", :name => "Skødstrup", },
                { :code => "8543", :name => "Hornslet", },
                { :code => "8544", :name => "Mørke", },
                { :code => "8550", :name => "Ryomgård", },
                { :code => "8560", :name => "Kolind", },
                { :code => "8570", :name => "Trustrup", },
                { :code => "8581", :name => "Nimtofte", },
                { :code => "8585", :name => "Glesborg", },
                { :code => "8586", :name => "Ørum Djurs", },
                { :code => "8592", :name => "Anholt", },
                { :code => "8600", :name => "Silkeborg", },
                { :code => "8632", :name => "Lemming", },
                { :code => "8641", :name => "Sorring", },
                { :code => "8653", :name => "Them", },
                { :code => "8654", :name => "Bryrup", },
                { :code => "8660", :name => "Skanderborg", },
                { :code => "8670", :name => "Låsby", },
                { :code => "8680", :name => "Ry", },
                { :code => "8870", :name => "Langå", },
                { :code => "8882", :name => "Fårvang", },
                { :code => "8883", :name => "Gjern", },
                { :code => "8900", :name => "Randers", },
                { :code => "8920", :name => "Randers NV", },
                { :code => "8930", :name => "Randers NØ", },
                { :code => "8940", :name => "Randers SV", },
                { :code => "8960", :name => "Randers SØ", },
                { :code => "8950", :name => "Ørsted", },
                { :code => "8961", :name => "Allingåbro", },
                { :code => "8963", :name => "Auning", },
                { :code => "8970", :name => "Havndal", },
                { :code => "8981", :name => "Spentrup", },
                { :code => "8983", :name => "Gjerlev J", },
                { :code => "8990", :name => "Fårup", },
                { :code => "9550", :name => "Mariager", }])
